import typing


class EventsProviderProtocol(typing.Protocol):
    async def events(self, changed_at: str, cursor: str | None = None) -> dict: ...
    async def register(
        self, event_id: str, first_name: str, last_name: str, email: str, seat: str
    ) -> str: ...
    async def get_seats(self, event_id: str) -> list[str]: ...


class EventRepositoryProtocol(typing.Protocol):
    async def get(self, event_id: str) -> typing.Any | None: ...
    async def upsert(self, event_data: dict) -> None: ...


class TicketRepositoryProtocol(typing.Protocol):
    async def create(self, event_id: str, ticket_id: str, user_data: dict) -> None: ...
