"""Initial migration

Revision ID: a8f2f7c5a9d1
Revises: b8dd9ea9dbaf
Create Date: 2026-04-01 17:28:13.081310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f2f7c5a9d1'
down_revision: Union[str, Sequence[str], None] = 'b8dd9ea9dbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
