"""Initial migration

Revision ID: b8dd9ea9dbaf
Revises: c39ec0c56e37
Create Date: 2026-04-01 17:14:12.939261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dd9ea9dbaf'
down_revision: Union[str, Sequence[str], None] = 'c39ec0c56e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('places', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'created_at')
    op.drop_column('places', 'changed_at')
    # ### end Alembic commands ###
